"""empty message

Revision ID: e1692780afe6
Revises: 59b8437bcc9a
Create Date: 2019-11-26 16:30:45.452351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1692780afe6'
down_revision = '59b8437bcc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.drop_column('movies', 'release_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###
